### ISSUE TITLE
Training time ?

### ISSUE THREAD

**Issue by francqz31** [yuguochencuc/BAE-Net#1]
What is the training time of BAE and the GPU that was used ? Biggest problem for Aero to me was that it was training so slowly on multiple high end Gpus.

**Comment by yuguochencuc** [comment]
> What is the training time of BAE and the GPU that was used ? Biggest problem for Aero to me was that it was training so slowly on multiple high end Gpus.
The training time of BAE-Net and BAE-Net-lite is much faster than Aero. We train on v100 GPU with batch-size is set to 8, each audio is set to 6s, and training an iteration(batch-size8) is about 1.45s.
