### ISSUE TITLE
how do you implement your conv1d

### ISSUE THREAD

**Issue by l6chen** [yuguochencuc/BAE-Net#4]
Hi, I noticed that the numbers of output channels match nFFT in your network. So did your directly treat frequency bin as channel dimension? Or you actually implement conv1d with conv2d while the stride of time dim is 1?
I reproduce your work in the 8-16k task, but the results are not as good as expected. So could your release your code, or at least your inference code and checkpoint. This may help a lot, Thanks in advanced!

**Comment by yuguochencuc** [comment]
> Hi, I noticed that the numbers of output channels match nFFT in your network. So did your directly treat frequency bin as channel dimension? Or you actually implement conv1d with conv2d while the stride of time dim is 1? I reproduce your work in the 8-16k task, but the results are not as good as expected. So could your release your code, or at least your inference code and checkpoint. This may help a lot, Thanks in advanced!

Hello, in my work, I used conv1d directly, with the frequency dimension as the channel dimension. I will open source the training and inference code for bae-net-lite after the paper is published. (I will also open source the BAE-Net-lite inference code first sometime in the near future).

**Comment by l6chen** [comment]
Great! Thanks for your work and wish your paper accepted soon!
